Document: skel
Title: Debian skel Manual
Author: <insert document author here>
Abstract: This manual describes what skel is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/skel/skel.sgml.gz

Format: postscript
Files: /usr/share/doc/skel/skel.ps.gz

Format: text
Files: /usr/share/doc/skel/skel.text.gz

Format: HTML
Index: /usr/share/doc/skel/html/index.html
Files: /usr/share/doc/skel/html/*.html
